name: Connect CI Check

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: check structure
        run: ls css js