name: CD Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: build step
        run: echo "Building app..."

      - name: deploy step
        run: echo "Deploying app 🚀"